# Generated by Django 4.1.3 on 2022-12-06 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblogs', '0002_alter_user_bio_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='<django.db.models.fields.related.ForeignKey>/posts/'),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/<django.db.models.fields.CharField>/'),
        ),
    ]
