# Generated by Django 4.1.3 on 2022-12-06 01:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblogs', '0003_post_image_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='image',
            new_name='profile_pic',
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(max_length=280, validators=[django.core.validators.MinLengthValidator(limit_value=1, message='Why would you want to post an empty message')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Username must consist of at least three alphanumericals', regex='^\\w{3,}$')]),
        ),
    ]
